spring.application.name=MyPortfolio
spring.datasource.url=jdbc:postgresql://ep-super-block-abhckaiv-pooler.eu-west-2.aws.neon.tech/portfolio?sslmode=require&channel_binding=require
spring.datasource.password=npg_OcLmB6Red3Fs
spring.datasource.username=neondb_owner
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor=org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always

portfolio.schedule.open=08:00
portfolio.schedule.close=17:00



